spring.application.name=fidentBank

# Conexão com o Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/fident_db
spring.datasource.username=adm
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Dialeto PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true